### PR TITLE
Fix entity rendering in report when value is an entity

### LINKED ISSUE #855: HTML Report should render entities, not only literals
Right now, report only renders values that are literals. I think it would be nice if entities were rendered the same way as in the other two columns.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #855

- [ ] `docs/` have been added/updated
- [ ] tests have been added/updated
- [ ] `mvn verify` says all tests pass
- [ ] `mvn site` says all JavaDocs correct
- [x] `CHANGELOG.md` has been updated

Oddly enough, the Manchester render doesn't like `OWLObjects` so I switched the Violations to use `OWLEntities` and now the values render correctly when they're not just literals.

### CODE REVIEW

File: robot-core/src/main/java/org/obolibrary/robot/ReportOperation.java [hunk 1]
```diff
@@ -944,13 +944,14 @@ private static String getQueryResultOrNull(QuerySolution qs, String var) {
         OWLEntity e = dataFactory.getOWLClass(ioHelper.createIRI(property));
         if (value != null) {
           IRI valIRI = ioHelper.createIRI(value);
-          if (valIRI != null) {
-            violation.addStatement(e, valIRI);
+          if (valIRI != null && !valIRI.toString().contains(" ")) {
```
Comment (matentzn) [inline robot-core/src/main/java/org/obolibrary/robot/ReportOperation.java:947]: Seems like `!valIRI.toString().contains(" ")` should belong into ioHelper.createIRI()? Just a suggestion to push potential problems upstream.

**Review by matentzn — APPROVED** [review]
Nice!

File: robot-core/src/main/java/org/obolibrary/robot/ReportOperation.java (hunk 1 above)
Comment (beckyjackson) [reply robot-core/src/main/java/org/obolibrary/robot/ReportOperation.java:947]: I think you're right about this. I'll change it so that `IOHelper.createIRI` returns `null` if the IRI contains a space.

Comment (matentzn) [reply robot-core/src/main/java/org/obolibrary/robot/ReportOperation.java]: cool

**Review by jamesaoverton — APPROVED** [review]
