### PR TITLE
Fix template handling of full IRIs

### LINKED ISSUE #782: Template: IRIs, used as IDs, can't end with digits?
I just reran a workflow that I have been using for many months. ROBOT templating is one part of it.

Here's a made-up example of my template:

| class.col                                   | source_med_id                 | source_full_name                             |
|---------------------------------------------|-------------------------------|----------------------------------------------|
| TYPE                                        | ID                            | A http://www.w3.org/2000/01/rdf-schema#label |
| http://purl.obolibrary.org/obo/PDRO_0000024 | http://example.com/resource/1 | aspirin                                      |
| http://purl.obolibrary.org/obo/PDRO_0000024 | http://example.com/resource/2 | tylenol                                      |
| http://purl.obolibrary.org/obo/PDRO_0000024 | http://example.com/resource/3 | lithotabs                                    |

Which I would execute with

```Bash
robot -vvv template  --template numerical_rhs.tsv --output numerical_rhs.ttl
```
That used to work (v?), but now (ROBOT 1.7.2) I get

> 2020-12-01 18:02:36,117 DEBUG org.semanticweb.owlapi.utilities.Injector - Injecting values [[]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setIRIMappers(java.util.Set).
UNKNOWN ENTITY ERROR could not interpret 'http://example.com/resource/1' in row 3, column 2 ("ID") in table "numerical_rhs.tsv".
For details see: http://robot.obolibrary.org/template#unknown-entity-error
org.obolibrary.robot.exceptions.RowParseException: template#UNKNOWN ENTITY ERROR could not interpret 'http://example.com/resource/1' in row 3, column 2 ("ID") in table "numerical_rhs.tsv".
	at org.obolibrary.robot.Template.processRow(Template.java:731)
	at org.obolibrary.robot.Template.generateOutputOntology(Template.java:377)
	at org.obolibrary.robot.TemplateOperation.template(TemplateOperation.java:184)
	at org.obolibrary.robot.TemplateCommand.execute(TemplateCommand.java:148)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:59)

Replacing the terminal digits in the IDs with alphabetical characters solves the problem

| class.col                                   | source_med_id                 | source_full_name                             |
|---------------------------------------------|-------------------------------|----------------------------------------------|
| TYPE                                        | ID                            | A http://www.w3.org/2000/01/rdf-schema#label |
| http://purl.obolibrary.org/obo/PDRO_0000024 | http://example.com/resource/one | aspirin                                      |
| http://purl.obolibrary.org/obo/PDRO_0000024 | http://example.com/resource/two | tylenol                                      |
| http://purl.obolibrary.org/obo/PDRO_0000024 | http://example.com/resource/three | lithotabs                                    |

Does this seem plausible?

I get the same error when using CURIEs like "mydata:1" and  `--prefix  "mydata: http://example.com/resource/"`

But IRIs like http://example.com/resource/1___ are tolerated.

Also, it doesn't appear that the help URL http://robot.obolibrary.org/template#unknown-entity-error resolves to anything beside the top of the template page.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #782

- [ ] `docs/` have been added/updated
- [x] tests have been added/updated
- [x] `mvn verify` says all tests pass
- [ ] `mvn site` says all JavaDocs correct
- [x] `CHANGELOG.md` has been updated

In the issue, `http://example.com/resource/1` is not a *technically* a valid QName, and we updated the processing of IDs/IRIs in templates last May to make sure all IRIs were also valid QNames. This is because the writer would fail on invalid QNames, but it seems like it's only *certain* invalid QNames... Even though it's not valid, OWLAPI seems to still handle it OK as opposed to the CURIEs that were never expanded to IRIs (see https://github.com/ontodev/robot/issues/688).

The QName check in OWLAPI fails every time for `http://example.com/resource/1` so I made a hack around it with a new `isQName` method in IOHelper. It will still fail for CURIEs with undefined namespaces, as we expect.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
The code looks good, but you know what I'm going to say! :smile: We need some unit tests, please.

**Comment by beckyjackson** [comment]
Done!

File: robot-core/src/main/java/org/obolibrary/robot/IOHelper.java [hunk 1]
```diff
@@ -1198,6 +1211,64 @@ public void saveContext(File file) throws IOException {
...
+    return true;
+  }
+
+  /**
+   * Determine if the short form of an IRI contains invalid characters.
+   *
+   * @param iri IRI to check
+   * @return true if no invalid characters found
+   */
+  public static boolean shortFormIsValid(IRI iri) {
```
Comment (jamesaoverton) [inline robot-core/src/main/java/org/obolibrary/robot/IOHelper.java:1260]: Is valid what? CURIE? QName? String?

Comment (beckyjackson) [reply robot-core/src/main/java/org/obolibrary/robot/IOHelper.java:1260]: It validates that the short form does not contain invalid characters. I guess `shortFormContainsInvalidCharacters` (returns true on invalid) or something like that sounded too long to me but I can change it.

Comment (jamesaoverton) [reply robot-core/src/main/java/org/obolibrary/robot/IOHelper.java:1260]: My point is that there are no invalid characters in general, without saying what the standard is. There are invalid characters for a CURIE, or a QName, or an IRI, or a Python function name.

I'll think about it a little more and make changes myself.

**Comment by jamesaoverton** [comment]
I asked for three different error messages, but when I went to review this closely only two made sense to me, so I removed one.
